---
name: 'matlab: tests'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
  pull_request:
    branches: ['*']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [R2021a, R2023a]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2.1.1
      with:
        release: ${{matrix.version}}
    - name: Run commands
      uses: matlab-actions/run-command@v2.1.1
      with:
        command: results = 1 + 1;